### ISSUE TITLE
How to recreate figure 3 in the paper?

### ISSUE THREAD

**Issue by rht** [rauner/air-pollution#2]
The paper: https://www.nature.com/articles/s41558-020-0728-x.

I grepped for "co-benefit", "benefit" and found no result. I assume that the policy cost (x axis) is created with calcMorbidity.R?

I need to recreate that figure 3, for this working paper: https://www.imf.org/en/Publications/WP/Issues/2022/05/31/The-Great-Carbon-Arbitrage-518464. cc: @alissak

**Comment by rauner** [comment]
This repo is the air pollution specific one, for the general results repo please check this out: https://github.com/rauner/holistic-coal-exit

U could group this table by region and sum up the following cost components: 
HH_H_cost_total;ED_H_cost_total

https://raw.githubusercontent.com/rauner/holistic-coal-exit/master/results/lca_REMIND_monetization_end_pointscoal_exit.csv

**Comment by rht** [comment]
We are looking for specifically the air pollution one. The numbers we are looking for are the emissions intensity timeseries for the coal exit scenario. I will open a new issue for this one.
